<div>
    <?php if($order == null): ?>
    <h1>There is no order to show bank transfer details for</h1>
    <h1>Keine Buchung gefunden</h1>
    <p>Gehe zu <a href="<?php echo $this->url('product'); ?>">Produkte</a> und w&auml;hle dort
         Artikel aus.</p>
    <?php else: ?>
    <p>Bitte &uuml;berweise den Betrag an das folgende Konto:</p>
    <table class="table">
        <tr>
            <td>Kontoinhaber</td>
            <td>Jonglieren in Freiburg e. V.</td>
        </tr>
        <tr>
            <td>IBAN</td>
            <td>DE26 6805 0101 0012 0917 91</td>
        </tr>
        <tr>
            <td>BIC</td>
            <td>FRSPDE66XXX</td>
        </tr>
        <tr>
            <td>Bank</td>
            <td>Sparkasse Freiburg-N&ouml;rdlicher Breisgau</td>
        </tr>
        <tr>
            <td>Betrag</td>
            <td><?php echo $this->currencyFormat($order->getSum(), 'EUR', null, 'de_DE'); ?></td>
        </tr>
        <tr>
            <td>Verwendungszweck</td>
            <td><?php echo $order->getCode()->getValue(); ?></td>
        </tr>
    </table>
    
    <p>
        Bitte achte darauf, als Verwendungszweck der &Uuml;berweisung
        <strong><?php echo $order->getCode()->getValue(); ?></strong>
        anzugeben. Ansonsten k&ouml;nnen wir die Zahlung nicht zuweisen und die Buchung kann nicht bearbeitet werden.
    </p>

    <?php endif; ?>
</div>
