<?php

if($emptycart) :
    $title = 'Der Einkaufswagen wurde geleert';
    $this->headTitle($title);
    $this->headMeta()->appendHttpEquiv('Refresh', '3;URL='.$this->url('product'));?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>

    <p>Du wirst weitergeleitet, bitt <a href="<?php echo $this->url('product') ?>">hier</a> klicken, falls dein Browser dich nicht weiterleitet.</p>
<?php 
else:
    $title = 'Einkaufswagen und persönliche Angaben leeren';
    $this->headTitle($title);
    ?>

    <h1><?php echo $this->escapeHtml($title); ?></h1>

    <p>Bist du sicher, dass du den Einkaufswagen und die Liste der Personen leeren m&ouml;chtest?</p>
    
    <?php
    #$obj = $form->getObject();
    $form->setAttribute('action', $this->url('cart', array('action' => 'reset')))
          ->prepare();

    echo $this->form()->openTag($form);

    echo $this->formHidden($form->get('csrf'));
    echo $this->formElement($form->get('submit')); ?>

    <a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Cancel</a>

    <?php echo $this->form()->closeTag(); ?>

<?php endif;


