<?php

$title = 'Danke';
$this->headTitle($title);
?>

<div class="jumbotron">
    <h1><span class="green"><?php echo $this->escapeHtml($title); ?></span></h1>
    
    <p>...f&uuml; die Bestellung und Deine Unterst&uuml;tzung der Freiburger Jonglierconvention.</p>
    
    <p>Wir verschicken eine Best&auml;tigungsmail mit weiteren Informationen.</p>

    <p><strong>Hinweis:</strong> Um die Best&auml;tigungsmail korrekt zu erhalten,
        ist es wichtig die Emailadresse orga@jonglieren-in-freiburg.de 
        zum Addressbuch hinzuzuf&uuml;gen. 
    </p>

    <p>Falls Du die Best&auml;tigungsmail nicht erhalten solltest, schau bitte zun&auml;chst im Spam-Ordner nach.
       Falls sie auch dort nicht ist, kontaktiere uns bitte unter <a href='mailto:orga@jonglieren-in-freiburg.de'>orga@jonglieren-in-freiburg.de</a>.</p>
</div>
