<?php

$title = 'Meine Buchung';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="row">
    <div class="col-lg-6">
        <div class="order-info">
            <h1>K&auml;ufer</h1>
            <?php $buyer = $order->getBuyer(); ?>
            <h2><?php echo $buyer->getFirstname().' '.$buyer->getSurname(); ?></h2>
            <p>er K&auml;ufer wird alle e-Tickets f&uuml;r alle registrierten Teilnehmer erhalten. Falls f&uuml;r einen Teilnehmer eine Emailadresse angegeben wurde wird dieser informiert, sobald das Ticket bezahlt ist, und kann dann das e-Ticket ebenfalls herunterladen.</p>
            <h3>Alle Informationen gehen an: <?php echo $buyer->getEmail(); ?></h3>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="order-info">
            <h1>Zahlungsart</h1>
            <?php if($order->getPaymentStatus() == 'paid') : ?>
            <div class="alert alert-success"><i class="fa fa-check"></i> Buchung ist bezahlt</div>
            <?php elseif($order->getPaymentStatus() == 'unpaid') : ?>
            <div class="alert alert-warning"><i class="fa fa-warning"></i> Buchung ist nicht bezahlt</div>
            <?php elseif($order->getPaymentStatus() == 'cancelled') : ?>
            <div class="alert alert-danger"><i class="fa fa-close"></i> Buchung ist storniert</div>
            <?php endif; ?>
            <?php $paymenttype = $order->getPaymentType(); ?>
            <h3><?php echo $paymenttype->getName(); ?></h3>
            <p><?php echo $paymenttype->getExplanation(); ?></p>
            <?php #if($order->getStatus() == 'paid'): ?>
            <?php if($order->getStatus()->getValue() == 'paid'): ?>
                <h3>Diese Buchung ist bezahlt</h3>
                <p>Die e-Tickets werden in K&uuml;rze versandt.</p>
                <p><strong>Achtung:</strong> Bitte f&uuml;ge die Emailadresse 
                    anmeldung@jonglieren-in-freiburg.de zum Adressbuch hinzu, um eine Einordnung der Email als Spam zu vermeiden.</p>
            <?php elseif($order->getStatus()->getValue() == 'ordered'): ?>
            <?php #if($order->getStatus() == 'unpaid'): ?>
                <?php if($paymenttype->getType() == 'BankTransfer'): ?>
                    <h3>&Uuml;berweisungsinformationen</h3>
                    <?php echo $this->partial('partial/banktransfer-info.phtml', array('order' => $order)); ?>
                <?php elseif($paymenttype->getType() == 'CreditCard'): ?>
                    <a class="btn btn-primary" href="<?php echo $this->url('payment', array('action' => 'creditcard', 'hashkey' => $order->getHashKey())); ?>">
                        Start payment with Credit Card
                    </a>
                <?php elseif($paymenttype->getType() == 'IPayment'): ?>
                    <a class="btn btn-primary" href="<?php echo $this->url('payment', array('action' => 'ipayment', 'hashkey' => $order->getHashKey())); ?>">
                        Start payment with Credit Card
                    </a>
                <?php else: ?>
                    No payment type was recognized (<?php echo $paymenttype->getType(); ?>)
                <?php endif; ?>
            <?php else: ?>
                <h3>Buchungsstatus unbekannt</h3>
                <p>Bitte kontaktiere die Organisatoren um das Problem zu l&ouml;sen: <a href="mailto:info@jonglieren-in-freiburg.de">info@jonglieren-in-freiburg.de</a></p>
            <?php endif; ?>
        </div>
    </div>
</div>
<div>
    <h1>Einkaufswagen</h1>
        <div>
        <?php 
            $sum = 0;
            foreach ($order->getPackages() as $package) : 
                if(count($package->getItems()) == 0) {
                    continue;
                }
                $user = $package->getParticipant();
            
                if($user->getFirstname() == '' && $user->getSurname() == '') :
                    $participant = 'unassigned items';
                else:
                    $participant = $user->getFirstname().' '.$user->getSurname();
                endif;
        ?>
            <div class="package">
                <h3><?php echo $participant; ?></h3>
                
                <?php if(count($package->getItems()) != 0): ?>
                <table class="table">
                    <tr>
                        <th>Produkte</th>
                        <th class="cart-amount">Anzahl</th>
                        <th class="cart-price">Preis</th>
                    </tr>
                    <?php
                    $subtotal = 0;
                    foreach ($package->getItems() as $item) : 
                        $subtotal += $item->getPrice();
                        $sum += $item->getPrice();
                        ?>
                        <tr>
                            <td>
                                <span class="product-name"><?php echo $item->getName(); ?></span>
                                <span class="product-variants">
                                    <?php 
                                    $variants = array();
                                    if(count($item->getItemVariants()) > 0): 
                                    ?>
                                    (
                                    <?php 
                                    $numVariants = count($item->getItemVariants()); 
                                    $i = 0;
                                    ?>
                                    <?php foreach($item->getItemVariants() as $variant): 
                                        echo $variant->getName().': '.$variant->getValue(); 
                                        if(++$i != $numVariants):
                                            echo '; ';
                                        endif;
                                        $variants[$variant->getName()] = $variant->getProductVariantValueId();
                                    endforeach; ?>
                                    )
                                    <?php endif; ?>
                                </span>
                            </td>
                            <td><?php echo $item->getAmount(); ?></td>
                            <td><?php echo $this->currencyFormat($item->getPrice(), 'EUR', null, 'de_DE'); ?></td>
                        </tr>
                    <?php endforeach; ?>
                    <tr>
                        <td></td>
                        <td>Zwischensumme:</td>
                        <td><?php echo $this->currencyFormat($subtotal, 'EUR', null, 'de_DE'); ?></td>
                    </tr>
                </table>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
        <?php if($paymenttype) : ?>
            <table class="table sum-table">
                <tr>
                    <td>Bestellwert:</td>
                    <td><?php echo $this->currencyFormat($order->getPrice(), 'EUR', null, 'de_DE'); ?></td>
                </tr>
                <tr>
                    <td>Geb&uuml;hren:</td>
                    <td><?php echo $this->currencyFormat($paymenttype->calcFee($sum), 'EUR', null, 'de_DE'); ?></td>
                </tr>
                <tr>
                    <th><span style="font-size: 18px;">Summe:</span></th>
                    <th><span style="font-size: 18px;"><?php echo $this->currencyFormat($order->getSum(), 'EUR', null, 'de_DE'); ?></span></th>
                </tr>
            </table>
        <?php endif; ?>
    </div>
</div>
<div class="clear-both"></div>
