<?php

$this->headTitle('Terms & Conditions');
?>

<div>
    <div class="jumbotron">
        <h1>Impressum</h1>
        <p>Jonglieren in Freiburg e.V.<br />
        Schlossweg 1<br />
        79294 S&ouml;lden</p>

        <p>E-Mail: info (at) jonglieren-in-freiburg.de<br />
        Internet: www.jonglieren-in-freiburg.de</p>

        <p>Vertretungsberechtiger Vereinsvorstand:
            <ul>
                <li>Dominik Selugga</li>
                <li>Alexander Koch</li>
                <li>Markus Zimmermann</li>
            </ul>
        </p>
        <p>Registergericht/-nummer: Amtsgericht Freiburg im Breisgau / VR 3728</p>
    </div>
</div>
