<?php

$this->headTitle('Terms & Conditions');
?>

<div>
    <a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Back</a>
    <div class="jumbotron">
        <h1>Gesch&auml;ftsbedingungen und Datenschutzerkl&auml;rung</h1>
        <a href="/AGBs.pdf" target="_blank">Gesch&auml;ftsbedingungen</a><br />
        <a href="/Datenschutzerklaerung.pdf" target="_blank">Datenschutzerkl&auml;rung</a>
    </div>
</div>
