<?php

$title = 'Person löschen';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php $participant = $form->getObject(); ?>
<p>Bist du sicher, dass der Teilnehmer
    <strong><?php echo $this->escapeHtml($participant->getFirstname().' '.$participant->getSurname()); ?></strong> gel&ouml;scht werden soll?
</p>
<?php if(count($package->getItems()) > 0): ?>
    <h2>Diese Artikel werden zusammen mit dem Teilnehmer gel&ouml;scht:</h2>
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Preis</th>
        </tr>
    
    <?php foreach($package->getItems() as $item): ?>
        <tr>
            <td><?php echo $item->getName(); ?></td>
            <td><?php echo $this->currencyFormat($item->getPrice(), 'EUR', null, 'de_DE'); ?></td>
        </tr>
    <?php endforeach; ?>
    </table>
<?php endif; ?>
    
<?php $form->setAttribute('action', $this->url('participant', array('action' => 'delete', 'id' => $participant->getId())))
      ->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('csrf'));
echo $this->formElement($form->get('submit')); ?>

<a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Abbrechen</a>

<?php echo $this->form()->closeTag();
