<?php

$title = 'Person ändern';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'participant',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();
#$form->getInputFilter()->get('email')->setRequired(false);

echo $this->form()->openTag($form);
#echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('id'));
?>
<div class="row">
    <div class="col-md-4">
        <div class="row">
            <div class="col-md-6">
                <?php echo $this->formRow($form->get('firstname')); ?>
            </div>
            <div class="col-md-6">
                <?php echo $this->formRow($form->get('surname')); ?>
            </div>
        </div>
        <?php echo $this->formRow($form->get('birthday'));
        echo $this->formRow($form->get('email'));
        echo $this->formRow($form->get('Country_id')); ?>
    </div>
    <div class="col-md-5">
        <p><strong>Hinweis zur Emailadresse:</strong> Wenn eine Emailadresse angegeben
            wird erh&auml;lt die Person eine Kopie ihres e-Tickets.</p>
        <p><strong>Hinweis f&uuml;r den K&auml;ufer:</strong> Die Person, die den Kauf
            durchf&uuml;hrt, erh&auml;lt automatisch alle bestellten e-Tickets. Daf&uuml;r 
            ist die Angabe der Emailadresse n&ouml;tig.</p>
        <p><strong>Hinweis zur &Auml;nderung:</strong> Die Angaben dieser Person k&ouml;nnen
            jederzeit im Men&uuml;punkt "Pers&ouml;nliche Angaben" ge&auml;ndert werden.</p>
    </div>
    <div class="col-md-3"></div>
</div>
<?php
echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
?>
<a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options); ?>">Abbrechen</a>
<?php
echo $this->form()->closeTag();
