<?php
    $ejc_with_year = "Freiburger Jonglierconvention 2016";
    $ejc_with_number = "18. Freiburger Jonglierconvention";
    $ejc_info_mail = "orga@jonglieren-in-freiburg.de";
    $ejc_website = "http://www.jonglieren-in-freiburg.de";
?>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
</head>
<body>
<div style="font-family: sans-serif;">
    <p>Liebe(r) <?php echo $order->getBuyer()->getFirstname().' '.$order->getBuyer()->getSurname(); ?>,</p>

    <p>Dies ist die Best&auml;tigung f&uuml;r
        <a href="<?php echo $this->url('order', array(
            'action' => 'view',
            'hashkey' => $order->getHashKey()
        ), array('force_canonical' => true)); ?>">Deine Bestellung</a>
        vom <?php echo $order->getCreated()->format('d.m.Y'); ?> mit der
        Buchungsnummer <b><?php echo $order->getCode()->getValue(); ?></b>.
        Danke, dass Du dich f&uuml;r die <?php echo $ejc_with_number; ?> angemeldet hast!
    </p>

    <!-- <p>You've chosen <?php echo $order->getPaymentType()->getName(); ?> as payment method.</p> -->

    <?php
    $paymenttype = $order->getPaymentType();
    if($paymenttype->getType() == 'BankTransfer'): ?>

        <p>Bitte &uuml;berweise den Betrag bis 23.06., um die Buchung abzuschlie&szlig;en.</p>

        <?php echo $this->partial('partial/banktransfer-info.phtml', array('order' => $order)); ?>

        <p>
            Um zu sehen, ob wir die Zahlung bereits erhalten haben, kannst Du diesem Link folgen:
            <a href="<?php echo $this->url('order', array(
                'action' => 'view',
                'hashkey' => $order->getHashKey()
            ), array('force_canonical' => true)); ?>">Deine Buchungsinformationen</a>
        </p>

    <?php endif; ?>

    <p>
        Bitte beachte die allgemeinen
        <a href="<?php echo $this->url('info',
                array('action' => 'terms'),
                array('force_canonical' => true)
            ); ?>">Gesch&auml;ftsbedingungen</a>,
        die an diese Email angeh&auml;ngt sind.
        Um die Dokumente zu lesen ben&ouml;tigst Du den Adobe Acrobat Reader, den Du hier herunterladen kannst:
        <a href="http://get.adobe.com/reader">http://get.adobe.com/reader</a>
    </p>

    <p>
        Alle Tickets k&ouml;nnen w&auml;hrend des Festivals an der Conventionkasse abgeholt werden. Vorbestellte Einzeltickets f&uuml;r die Gala-Show k&ouml;nnen zus&auml;tzlich am 25.06.2016 ab 19 Uhr an der Abendkasse im B&uuml;rgerhaus Z&auml;hringen abgeholt werden.
    </p>

    <p>Bitte beachtet, dass wir <b>f&uuml;r Minderj&auml;hrige, die ohne ihre Erziehungsberechtigten an dem Festival teilnehmen 
        m&ouml;chten</b>, eine schriftliche Erkl&auml;rung eines Erziehungsberechtigten ben&ouml;tigen, aus der die Erlaubnis zur 
        Teilnahme hervorgeht, in der au&szlig;erdem (wie bei allen Teilnehmern) die Haftung für Verletzungen durch die Organisatoren 
        ausgeschlossen wird, und in der idealerweise auch eine Betreuungsperson benannt wird! Das Formular dazu findet ihr im Anhang 
        oder unter <a href="http://www.jonglieren-in-freiburg.de/?page_id=395">http://www.jonglieren-in-freiburg.de/?page_id=395</a>.
    </p>

    <p style="color: #f48029;"><b>
        Bis bald in Freiburg, vom 24. bis 26. Juni zur <?php echo $ejc_with_year; ?>!
    </b></p>

    <p>Liebe Gr&uuml;&szlig;e,</p>

    <p>Dein Orga-Team.</p>

    <hr>
    <p>
        Du hast folgende Produkte gekauft
        (bestellt von <?php echo $order->getBuyer()->getFirstname().' '.$order->getBuyer()->getSurname(); ?>):
    </p>

    <?php echo $this->partial('partial/order-info.phtml', array('order' => $order)); ?>

    <div style="width: 100%;
            text-align: center;
            padding: 1em;
            background-color: #eeeeee;">
        Falls Du Fragen zur Voranmeldung hast, bitte kontaktiere uns unter
        <a href='mailto:prereg@eja.net'>orga@jonglieren-in-freiburg.de</a>.
        <br>
        F&uuml;r weitere Informationen &uuml;ber die <?= $ejc_with_year ?>,
        besuche bitte <a href='<?= $ejc_website ?>'><?= $ejc_website ?></a>
        oder schreibe an <a href='mailto:<?= $ejc_info_mail ?>'><?= $ejc_info_mail ?></a>.
    </div>
</div>
</body>
</html>
