<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <style type="text/css">
            * {
                font-family: sans-serif;
            }
            .header, .footer {
            	width: 100%;
            	text-align: center;
            	padding: 1em;
            }
            .header {
            	margin-top: 0px;
            	background-color: #85b32a;
            	color: #fff;
            }
            .clear-both {
                clear: both;
            }
            .header > a {
            	color: #fff;
            	font-weight: bold;
            	text-decoration: none;
            }
            .footer {
            	background-color: #eeeeee;
            }
        </style>
    </head>
    <body>
        <div class='header'>Freiburger Jonglierfestival 2016 - 24.-26. Juni - <a href='http://www.jonglieren-in-freiburg.de'>www.jonglieren-in-freiburg.de</a></div>

        <p>Hallo <?php echo $order->getBuyer()->getFirstname().' '.$order->getBuyer()->getSurname(); ?>,</p>

        <p>sch&ouml;n, dass Du dich am <?php echo $order->getCreated()->format('d.m.Y') ?> zum 18. Freiburger Jonglierfestival 2016 angemeldet hast!
        Leider wurde(n) Dein(e) Ticket(s) noch nicht bezahlt. Wir bitten Dich,
        dies innerhalb von 7 Tagen nachzuholen, da Deine Voranmeldung erst mit der Bezahlung der Tickets abgeschlossen ist!</p>

        <?php echo $this->partial('partial/banktransfer-info.phtml', array('order' => $order)); ?>

        <p>
            Um zu sehen, ob wir die Zahlung bereits erhalten haben, kannst Du diesem Link folgen:
            <a href="<?php echo $this->url('order', array(
                'action' => 'view',
                'hashkey' => $order->getHashKey()
            ), array('force_canonical' => true)); ?>">Deine Buchungsinformationen</a>
        </p>

        <p>Falls Du bereits bezahlt hast, Du Deine Bestellung stornieren oder &auml;ndern m&ouml;chtest oder Du andere Fragen zur Voranmeldung hast, schicke
        bitte eine Email an <a href='mailto:orga@jonglieren-in-freiburg.de'>orga@jonglieren-in-freiburg.de</a>.</p>

        <p>Vielen Dank und die besten Gr&uuml;&szlig;e aus Freiburg!</p>

        <p>Dein Orga-Team</p>
    </body>
</html>
