<?php

if($order == null) :
$title = 'Zahlungsinformation konnte nicht gefunden werden';
$this->headTitle($title);
?>
<div class="jumbotron">
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <p>Das System konnte die zugeh&ouml;rige Buchung zu dieser Zahlungsinformation
        nicht finden. Mit der Buchung wurde eine Email mit allen n&ouml;tigen Daten
        verschickt. Bitte nutze den Link in dieser Email.</p>
</div>
<?php 
else:

$title = 'Zahlung per Banküberweisung/Barzahlung';
$this->headTitle($title);
?>
<div class="jumbotron">
    <h1><?php echo $this->escapeHtml($title); ?></h1>

    <?php echo $this->partial('partial/banktransfer-info.phtml', array('order' => $order)); ?>

    <p>Wir haben diese Information an die folgende Emailadresse geschickt: <strong><?php echo $order->getBuyer()->getEmail(); ?></strong></p>

    <p>
        Du kannst diese Information erneut aufrufen, indem du
        <a href="<?php echo $this->url('order', array('action' => 'view', 'hashkey' => $order->getHashKey())); ?>">diesen Link</a> speicherst,
        oder du kannst die Email aufrufen, die wir dir geschickt haben.
    </p>

    <p class="orange"><strong>Danke f&uuml;r die Voranmeldung, bis bald in Freiburg!</strong></p>
</div>
<?php endif;
