<?php $this->headTitle($product->getName()); ?>
<a href="<?php echo $this->url($breadcrumb->route, $breadcrumb->params, $breadcrumb->options);?>"><?php echo $this->translate('zurück zur Übersicht'); ?></a>
<?php if($chooser && false): ?>
<div class="p_overlay">
    <div class="p_overlay_inner">
        <h3>
            Added <span class="green"><?php echo $product->getName(); ?></span> to your shopping cart.
        </h3>
        <div class="row">
            <div class="col-sm-6">
                <p><a class="btn btn-primary" href="<?php echo $this->url('product'); ?>"><i class="fa fa-caret-left"></i> mehr Produkte hinzuf&uuml;gen</a></p>
                <p><a class="btn btn-primary" href="<?php echo $this->url(
                    $bc_stay->route, 
                    $bc_stay->params, 
                    $bc_stay->options
                    ); ?>"><i class="fa fa-caret-left"></i> dieses Produkt erneut hinzuf&uuml;gen</a></p>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-primary pull-right" href="<?php echo $this->url('order'); ?>">Einkaufswagen <i class="fa fa-caret-right"></i></a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>

<?php if(count($product->getProductPrices()) == 0): ?>
    <p class="desc-short">Dieses Produkt ist nicht verf&uuml;gbar</p>
<?php else: ?>
<div class="product-view">
    <?php
    $form = $this->form;
    $form->prepare();

    echo $this->form()->openTag($form); ?>
    <div class="row">
        <div class="col-md-5" style="text-align: center; margin: 20px 0;">
            <!--<i class="fa fa-file-text-o product-icon-lg"></i>-->
            <i class="fa fa-ticket product-icon-lg"></i>
            <!--<img src="/img/no-available-image.png" alt="No available image" width="200">-->
        </div>
        <div class="col-md-7">
            <div class="row">
                <div class="col-md-12">
                    <h1><?php echo $this->escapeHtml($product->getName()); ?></h1>
                </div>
            </div>
            <?php if($formfail): ?>
            <div class="row">
                <div class="alert alert-danger">
                    <p>Bitte das gesamte Formular ausf&uuml;llen, um dieses Produkt in den Einkaufswagen zu legen.</p>
                </div>
            </div>
            <?php endif; ?>
            <div class="row">
                <div class="col-md-6">
                    <p class="desc-short"><?php echo $product->getShortDescription(); ?></p>
                    <?php echo $product->getLongDescription(); ?>
                </div>
                <div class="col-md-6">
                    <?php if($product->getPriceCount() != 1): ?>
                        <p class="small text-right">Diese Preise gelten für die Voranmeldung bis<br><?php echo $deadline->getDeadline()->format('d.m.Y H:i:s T'); ?></p>
                    <?php endif; ?>
                    <?php echo $this->partial('partial/product-price.phtml', array('agegroups' => $agegroups, 'deadline' => $deadline, 'product' => $product)); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6 ui-tabs-panel ui-widget-content ui-corner-all">
                    <div id="person-detail">
                        <ul>
                            <?php # agegroup is disabled at all this year
                            if(!$product->getPersonalized() && $product->getPriceCount() != 1 && false): ?>
                                <li><a href="#agegroup">Altersgruppe</a></li>
                            <?php endif; ?>
                            <li><a href="#person">Person</a></li>
                        </ul>
                        <?php if(!$product->getPersonalized() && $product->getPriceCount() != 1 && false): ?>
                            <div id="agegroup">
                                <?php 
                                echo $this->formRow($form->get('agegroup_id')); 
                                /*
                                 * I need the empty participant_id here so the 
                                 * validator can work correctly
                                 */
                                echo $this->formHidden($form->get('participant_id'));
                                ?>
                            </div>
                        <?php endif; ?>
                        <div id="person">
                            <?php if($form->get('submit')->getAttribute('disabled') == 'disabled'): ?>
                                <div class="alert alert-warning">
                                    <h4>Bitte eine Person ausw&auml;hlen</h4>
                                    <p>Dies ist ein personalisiertes Ticket. Um fortzufahren, bitte erst 
                                        <a href="<?php echo $this->url('participant', array('action' => 'add')); ?>">eine Person anlegen</a>, die dieses Ticket benutzen wird.</p>
                                    <div class="clear-both"></div>
                                </div>
                            <?php 
                            else:
                                echo $this->formRow($form->get('participant_id'));
                            endif;
                            
                            /*
                             * I need the empty agegroup_id here so the 
                             * validator can work correctly
                             */
                            echo $this->formHidden($form->get('agegroup_id'));
                            ?>
                            <p><strong>Tip:</strong><br />Du kannst 
                                <!--<a href="<?php echo $this->url('participant', array('action' => 'add')); ?>">add a new person</a>-->
                                <a href="#" data-toggle="modal" data-target="#addParticipant">eine neue Person anlegen</a>
                                oder die Angaben jeder Person unter "Meine Personen" im Hauptmen&uuml; &auml;ndern.</p>
                        </div>
                    </div>

                    <?php $form->get('Product_id')->setAttribute('value', $product->getId());
                    echo $this->formHidden($form->get('Product_id'));
                    #$prices = $product->getProductPrices();

                    /*for($i = 0; $i<$form->getVariantCounter(); $i++) {
                        echo $this->formHidden($form->get('variant_id_'.$i));
                        echo $this->formRow($form->get('variant_value_'.$i));
                        echo $this->formRow($form->get('variant_type_'.$i));
                    }*/
                    
                    foreach($product->getProductVariants() as $variant) {
                        echo $this->formRow($form->get('pv['.$variant->getId().']'));
                    }
                    ?>
                    <p class="text-right">
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                    </p>
                </div>
                <div class="col-md-6">
                    <?php if(count($product->getChildProducts()) > 0): ?>
                    <h3>Einschlie&szlig;lich:</h3>
                    <?php foreach($product->getChildProducts() as $package): 
                        $child = $package->getSubProduct(); ?>
                        <h4><?php echo $child->getName(); ?></h4>
                        <?php foreach($child->getProductVariants() as $variant) :
                            echo $this->formRow($form->get('pv['.$variant->getId().']'));
                        endforeach;?>
                        
                    <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
</div>
<div id="addParticipant" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add new participant</h4>
            </div>
            <?php
            $participantForm = $this->participantForm;
            $participantForm->setAttribute('action', $this->url('participant', array('action' => 'add')));
            $participantForm->prepare();

            echo $this->form()->openTag($participantForm); ?>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <?php echo $this->formRow($participantForm->get('firstname')); ?>
                    </div>
                    <div class="col-md-6">
                        <?php echo $this->formRow($participantForm->get('surname')); ?>
                    </div>
                </div>
                <?php echo $this->formRow($participantForm->get('birthday'));
                echo $this->formRow($participantForm->get('email'));
                echo $this->formRow($participantForm->get('Country_id')); ?>

                
            </div>
            <div class="modal-footer">
                <?php echo $this->formSubmit($participantForm->get('submit')); ?>
                <button type="button" class="btn btn-default" data-dismiss="modal">Schlie&szlig;en</button>
            </div>
            <?php echo $this->formHidden($participantForm->get('csrf')); ?>    
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
<div id="chooser" class="modal fade<?php if($chooser) { echo ' in'; } ?>" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">
                    <span class="color-primary"><?php echo $product->getName(); ?></span> in den Einkaufwagen gelegt.
                </h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-6">
                        <p><a class="btn btn-primary" href="<?php echo $this->url('product'); ?>"><i class="fa fa-caret-left"></i> mehr Produkte hinzuf&uuml;gen</a></p>
                        <p><a class="btn btn-primary" href="<?php echo $this->url(
                            $bc_stay->route, 
                            $bc_stay->params, 
                            $bc_stay->options
                            ); ?>"><i class="fa fa-caret-left"></i> dieses Produkt erneut hinzuf&uuml;gen</a></p>
                    </div>
                    <div class="col-sm-6">
                        <a class="btn btn-primary pull-right" href="<?php echo $this->url('order'); ?>">Einkaufswagen <i class="fa fa-caret-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif;
