<?php

$title = 'Tickets für '.$ers_config['name_with_year'];
$this->headTitle($title);
?>
<?php if($deadline): ?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <div class="row">
        <div class="col-md-6">
            <p>Artikel ausw&auml;hlen, um weitere Infos hinzuzuf&uuml;gen und ihn in den Einkaufswagen zu legen. <b>Achtung:</b> Dieses Jahr haben wir bereits unerwartet viele Voranmeldungen f&uuml;r das Festival, so dass wir bei den <u>&Uuml;bernachtungs</u>kapazit&auml;ten
            an unsere Grenzen sto&szlig;en. Aus diesem Grund ist die Voranmeldung nun nochmals bis Donnerstag um Mitternacht ge&ouml;ffnet. Bitte meldet euch an, wenn ihr euch einen Schlafplatz
            sichern wollt! Zahlen k&ouml;nnt ihr dann auch noch vor Ort. Wer nicht angemeldet ist, dem k&ouml;nnen wir leider keinen &Uuml;bernachtungsplatz garantieren!</p>
            <p>Alle hier angebotenen Tickets k&ouml;nnen w&auml;hrend des Festivals an der Conventionkasse abgeholt werden. Vorbestellte Einzeltickets f&uuml;r die Gala-Show k&ouml;nnen zus&auml;tzlich am 25.06.2016 ab 19 Uhr an der Abendkasse im B&uuml;rgerhaus Z&auml;hringen abgeholt werden.</p>
        </div>
        <div class="col-md-6">
            <p class="text-right"></p>
        </div>
    </div>

    <?php 
    foreach ($products as $product) : 
        if(count($product->getProductPrices()) == 0):
            continue;
        endif;
    ?>
    <a class="product-item" href="<?php echo $this->url('product', array('action' => 'add', 'product_id' => $product->getId()));?>">
        <span class="product-title"><?php echo $product->getName(); ?></span>
        <span class="product-short-description"><?php echo $product->getShortDescription(); ?></span>
        <?php echo $this->partial('partial/product-price.phtml', array('agegroups' => $agegroups, 'deadline' => $deadline, 'product' => $product)); ?>
        <div class="clear-both"></div>
    </a>
    <hr />

    <?php endforeach;
else: ?>
    <div class="jumbotron">
        <h1>
            <?php echo $this->escapeHtml('Voranmeldung ist geschlossen'); ?>
        </h1>
        <div class="row">
            <div class="col-md-offset-2 col-md-8">
                <p>Die Voranmeldung ist geschlossen. Weitere Infos gibt es auf unserer Homepage <a href="<?php echo $ers_config['registration_info'] ?>"><?php echo $ers_config['registration_info'] ?></a></p>
            </div>
        </div>
    </div>
<?php endif;
