<?php

$title = 'Tickets für '.$ers_config['name_with_year'];
$this->headTitle($title);
?>
<?php if($deadline): ?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <div class="row">
        <div class="col-md-6">
            <p>Artikel auswählen, um weitere Infos hinzuzufügen und ihn in den Einkaufswagen zu legen.</p>
        </div>
        <div class="col-md-6">
            <p class="text-right">Diese Preise gelten für die Voranmeldung bis<br><?php echo $deadline->getDeadline()->format('d.m.Y H:i:s T'); ?></p>
        </div>
    </div>

    <?php 
    foreach ($products as $product) : 
        if(count($product->getProductPrices()) == 0):
            continue;
        endif;
    ?>
    <a class="product-item" href="<?php echo $this->url('product', array('action' => 'add', 'product_id' => $product->getId()));?>">
        <span class="product-title"><?php echo $product->getName(); ?></span>
        <span class="product-short-description"><?php echo $product->getShortDescription(); ?></span>
        <?php echo $this->partial('partial/product-price.phtml', array('agegroups' => $agegroups, 'deadline' => $deadline, 'product' => $product)); ?>
        <div class="clear-both"></div>
    </a>
    <hr />

    <?php endforeach;
else: ?>
    <div class="jumbotron">
        <h1>
            <?php echo $this->escapeHtml('Voranmeldung ist geschlossen'); ?>
        </h1>
        <div class="row">
            <div class="col-md-offset-2 col-md-8">
                <p>Die Voranmeldung ist geschlossen. Weitere Infos gibt es auf unserer Homepage <a href="<?php echo $ers_config['registration_info'] ?>"><?php echo $ers_config['registration_info'] ?></a></p>
            </div>
        </div>
    </div>
<?php endif;
